rootProject.name = "DameDame"
include(":app")
include(":domain")
include(":data")
include(":feature:notification")
include(":feature:write-diary")
include(":feature:auth")
include(":shared")
include(":core-ui")
include(":navigator")
